

CREATE TABLE IF NOT EXISTS TRACK (
	TRAIL VARCHAR(64) NOT NULL,
	INDEX INTEGER NOT NULL,
	TYPE INTEGER NOT NULL,
	PARENT INTEGER,
	BEGIN_TIME BIGINT NOT NULL,
	END_TIME BIGINT DEFAULT -1,
	VALUE VARCHAR,
	PRIMARY KEY(TRAIL, INDEX)
);

CREATE TABLE IF NOT EXISTS TAG (
	TRAIL VARCHAR(64) NOT NULL,
	INDEX INTEGER NOT NULL,
	TRACK_INDEX INTEGER NOT NULL,
	TIMESTAMP BIGINT NOT NULL,
	KEY VARCHAR,
	VALUE VARCHAR,
	PRIMARY KEY(TRAIL, INDEX)
);
